apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: k8s-observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-observability
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.0.13
    helm:
      releaseName: k8s-monitoring
      valuesObject:
        cluster:
          name: ${CLUSTER_NAME}
        
        destinations:
          - name: oltpGateway
            protocol: http
            type: otlp
            url: https://${ARGOCD_ENV_host}
            auth:
              type: basic
              usernameKey: "username"
              passwordKey: "apiKey"
            secret:
              create: false
              name: k8s-observability
              namespace: k8s-observability
            logs: { enabled: true }
            metrics: { enabled: true }
            traces: { enabled: true }

        applicationObservability:
          enabled: true
          receivers:
            otlp:
              enabled: true
              http:
                enabled: false
              grpc:
                enabled: true
        
        prometheusOperatorObjects:
          enabled: true
        
        podLogs:
          enabled: true

        traces:
          enabled: true
        alloy-metrics:
          enabled: true
          liveDebugging:
            enabled: true
          alloy:
            stabilityLevel: experimental
        
        alloy-logs:
          enabled: true
          liveDebugging:
            enabled: true
          alloy:
            stabilityLevel: experimental
          controller:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: eks.amazonaws.com/compute-type
                          operator: NotIn
                          values:
                            - fargate

        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP

  destination:
    server: "https://kubernetes.default.svc"
    namespace: k8s-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
