apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Kubernet Observability
  destinations:
    - name: in-cluster
      namespace: 'k8s-observability'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - k8s-observability
  sourceRepos:
    - https://grafana.github.io/helm-charts
